spring:
  datasource:
    url:
    username:
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    locations: classpath:db/migration,classpath:db/test-data
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

algafood:
  storage:
    local:
      diretorio-fotos:
    s3:
      id-chave-acesso:
      chave-acesso-secreta:
      bucket:
      regiao:
      diretorio-fotos:

